"""empty message

Revision ID: 002c4ace0296
Revises: 1dd99dd45323
Create Date: 2023-04-25 20:29:36.760801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002c4ace0296'
down_revision = '1dd99dd45323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('keyword1')
        batch_op.drop_column('keyword3')
        batch_op.drop_column('template')
        batch_op.drop_column('post9_16')
        batch_op.drop_column('keyword2')
        batch_op.drop_column('post1_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post1_1', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keyword2', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post9_16', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('template', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keyword3', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keyword1', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
