"""empty message

Revision ID: 5d52f4ae6867
Revises: dcff3e8dacff
Create Date: 2023-04-11 23:51:06.179375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d52f4ae6867'
down_revision = 'dcff3e8dacff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('cta')

    # ### end Alembic commands ###
